services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${USER_DB}
      POSTGRES_PASSWORD: ${PASSWORD_DB}
      PGDATA: /data/postgres
      POSTGRES_DB: ${NAME_DB}
    volumes:
      - db:/data/postgres
    ports:
      - "${PORT_DB}:5432"
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
networks:
  db:
    driver: bridge

volumes:
  db: